version: '3.9'

services:
  redis:
    container_name: redis
    image: redis
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 60s
      retries: 3
      start_period: 10s
    restart: always
  celery:
    image: cyber_fitness_bot:latest
    command: celery -A project worker  --autoscale=10,3 -l info
    env_file:
      - .env
    volumes:
      - ./app/logs:/home/app/web/logs
      - ./app/media:/home/app/web/media
    depends_on:
      redis:
        condition: service_started
    restart: always


  celery-beat:
    image: cyber_fitness_bot:latest
    command: celery -A project beat -l info
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
    restart: always

volumes:
  postgres_data:
  redis_data:
