# Generated by Django 4.2.18 on 2025-01-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='prefix',
            field=models.CharField(blank=True, default='general', max_length=100, null=True, verbose_name='префикс'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='value',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='значение'),
        ),
    ]
