# Generated by Django 4.2.18 on 2025-02-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_settings_prefix_alter_settings_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Настройка', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.AlterField(
            model_name='settings',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='prefix',
            field=models.CharField(blank=True, default='general', max_length=100, null=True, verbose_name='Префикс'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='value',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Значение'),
        ),
    ]
