# Generated by Django 4.2.18 on 2025-02-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_contract_cheque'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstate',
            name='has_contract',
            field=models.BooleanField(default=False),
        ),
    ]
