# Generated by Django 4.2.18 on 2025-02-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_userstate_has_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstate',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userstate',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userstate',
            name='patronymic',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
