# Generated by Django 4.2.18 on 2025-02-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_userstate_first_name_userstate_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstate',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='userstate',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userstate',
            name='patronymic',
        ),
    ]
