# Generated by Django 4.2.18 on 2025-02-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_circle'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstate',
            name='send_reports',
            field=models.BooleanField(default=False),
        ),
    ]
