# Generated by Django 4.2.18 on 2025-02-05 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_userstate_send_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstate',
            name='receive_notifications',
        ),
    ]
