# Generated by Django 4.2.18 on 2025-02-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_remove_userstate_receive_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('report_data', models.JSONField()),
                ('is_sent', models.BooleanField(default=False)),
                ('confirmed_by', models.ManyToManyField(blank=True, to='bot.userstate')),
            ],
        ),
    ]
