# Generated by Django 4.2.18 on 2025-02-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstate',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
