# Generated by Django 4.2.18 on 2025-02-18 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_alter_cheque_options_alter_circle_options_and_more'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE bot_userstate DROP COLUMN has_contract;"),
    ]
