# Generated by Django 4.2.18 on 2025-02-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_auto_20250218_0857'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
